import { Inter } from "next/font/google";
import "./globals.css";
import '../sass/main.scss'
import archivo from "../../public/fonts/archivoBlack";
import roboto from "../../public/fonts/roboto"

export const metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} ${roboto.variable}`}>{children}</body>
    </html>
  );
}
